# Generated by Django 5.2.4 on 2025-07-31 13:46

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (max 5MB, JPG/PNG)', null=True, upload_to=users.models.user_profile_picture_path),
        ),
    ]
