# Generated by Django 5.2.4 on 2025-07-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot image of the problem (optional)', null=True, upload_to='ticket_screenshots/'),
        ),
    ]
