# Generated by Django 5.2.4 on 2025-08-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ticket_status', 'Ticket Status Change'), ('new_comment', 'New Comment'), ('assignment', 'Ticket Assigned'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
