# Generated by Django 5.2.4 on 2025-08-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ticket_status', 'Ticket Status Change'), ('new_comment', 'New Comment'), ('assignment', 'Ticket Assigned'), ('new_ticket', 'New Ticket Created'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
